base_dmg: 2
base_munition: 1          
gravity: 5

explosion_radius: 1   



duck_speed: 3
duck_health: 3
duck_jump_force: 35     
duck_flap_force: 15
duck_flap_gravity: 3
duck_max_flaps : 5

item_respawn_time_sec: 5
box_health: 1

fps: 45
rounds_per_set: 4
wins_needed: 10


## Todavia no tomados en cuenta.
armor_health:  5   
helmet_health: 10    
